spring:
  ldap:
    embedded:
      base-dn: dc=testad,dc=local
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:test-server.ldif
      port: 8389
      validation:
        enabled: false